#default config
server:
  port: 8080
  compression.enabled: true
  compression.mime-types: application/json,text/html,text/xml,text/javascript,text/css,text/plain
  compression.min-response-size: 2048
  connection-timeout: 50000
  max-http-header-size: 8192
  tomcat.max-threads: 1000
  tomcat.accept-count: 300
  servlet:
    context-path: /ibeacon

#  tomcat.accesslog.directory: ${app.home}/logs
#  tomcat.accesslog.enabled: true
#  tomcat.accesslog.file-date-format: .yyyy-MM-dd-HH
#  tomcat.accesslog.pattern: '%h %l %u %t &quot;%r&quot; %s %b %Dms'

spring:
#Specify the DBMS
  jpa.database: MYSQL
#Show or not log for each sql query
  jpa.show-sql: true
  jpa.properties.hibernate.format_sql: true
#ManyToOne lazy
  jpa.properties.hibernate.enable_lazy_load_no_trans: true

#Jpa conn pool info
  datasource.url: jdbc:mysql://localhost:3306/ibeacon?useUnicode=true&characterEncoding=UTF-8&useSSL=true
  datasource.username: root
  datasource.password: root
  datasource.driver-class-name: com.mysql.jdbc.Driver
  datasource.driverClassName: com.mysql.jdbc.Driver
  datasource.max-idle: 15
  datasource.max-wait: 10000
  datasource.min-idle: 10
  datasource.initial-size: 10
  datasource.max-active: 300
  datasource.validation-query: SELECT 1
  datasource.test-on-borrow: false
  datasource.test-while-idle: true
  datasource.time-between-eviction-runs-millis: 30000
  datasource.min-evictable-idle-time-millis: 30000
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath\:/META-INF/resources/,classpath\:/resources/,classpath\:/static/images/,classpath\:/public/,file\:D:/Intellij Idea/
                      classpath:/static/images/,classpath:/public/,file:D:/Intellij Idea/



#  jpa.hibernate.ddl-auto: validate, update, create, create-drop
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

